version: '3.8'
services:
  auth:
    build: .
    ports:
      - "8383:8383"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - SERVER_PORT=8383
      - GITHUB_CLIENT_ID=Ov23licEPfBjzQdvCOIl
      - GITHUB_CLIENT_SECRET=ec1cedd8b1638df6d95e86c93f0a52012a897c15
      - GITHUB_REDIRECT_URL=http://localhost:8383/api/v1/auth/github/callback
    networks:
      - auth_network
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:
networks:
  auth_network:
    driver: bridge