basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_hse-revizor_auth-service_internal_pkg_models.GitHubUser:
    properties:
      created_at:
        description: Время создания записи
        example: "2024-03-20T15:04:05Z"
        type: string
      email:
        description: Email пользователя
        example: octocat@github.com
        type: string
      github_id:
        description: ID пользователя в GitHub
        example: 12345678
        type: integer
      id:
        description: ID пользователя в нашей системе
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      login:
        description: Логин пользователя в GitHub
        example: octocat
        type: string
      updated_at:
        description: Время последнего обновления
        example: "2024-03-20T15:04:05Z"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Swagger documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: auth Service API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Отображает страницу с кнопкой для входа через GitHub
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Домашняя страница
      tags:
      - auth
  /auth/github/callback:
    get:
      consumes:
      - application/json
      description: Обрабатывает ответ от GitHub после успешной авторизации
      parameters:
      - description: Код авторизации от GitHub
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hse-revizor_auth-service_internal_pkg_models.GitHubUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Callback от GitHub
      tags:
      - auth
  /login:
    get:
      consumes:
      - application/json
      description: Перенаправляет пользователя на страницу авторизации GitHub
      produces:
      - application/json
      responses:
        "307":
          description: Redirect to GitHub
          schema:
            type: string
      summary: Вход через GitHub
      tags:
      - auth
swagger: "2.0"
